
* nomenclatura
  - parcela :: un terreno con un solo cultivo (unica especie)
  - pedido especial :: son pedidos de uso de servicio de drones no
       cubiertos por el abono del usuario.
  - plan de servicio :: es el plan de servicio mensual del usuario,
       incluye toda la información de servicios incluidos y sus costos
       y el costo adicional por pedidos especiales de drones.
  - maquinaria :: se refiere a los distintos dispositivos actuadores
                  que maneja el sistema, que se refiere tanto a
                  maquinaria automatizada (cosechadoras, regadoras,
                  fumigadoras) como a maquinaria operada manualmente
                  por un operador.



* WBS Producto
1. módulo de gestión de terrenos

   permite gestionar y visulizar información estatica de los terrenos
   y sus cultivos.
   1. sistema de gestión de terrenos
   2. sistema de gestión de cultivos
      incluye la funcionalidad de ingreso de muestreos manuales, etc.
   3. sistema de visualización de salud
2. módulo de trazabilidad y auditoría
   provee una API (para ser usada por el resto de los modulos) que
   permite registrar las acciones importantes o criticas, registrando
   quién realizo la acción en qué momento y con qué parámetros.
3. módulo de gestión de dispositivos y servicios externos

   permite hacer ABM de los dispositivos conocidos por el sistema, o
   sea: maquinaria agricola, sistemas de drones, sistemas de
   estaciones meteorológicas
4. módulo de facturación

   controla el consumo realizado por los usuarios; controla los
   abonos; controla las facturas y pagos.

   1. sistema de gestión de abonos
   2. sistema de contabilidad de consumos
   3. sistema de emisión de facturas
   4. sistema de control de pagos recibidos
   5. sistema de emisión de pagos por uso de plan maestro
5. módulo de gestión de usuarios

   1. sistema de ABM de usuarios
   2. sistema de gestión de perfiles
6. módulo de ejecución de plan maestro

   planifica las acciones a ejecutar según los parámetros del terreno
   y el plan maestro, e invoca al módulo de actuación para llevar a
   cabo dichas acciones. Dado que este sistema es intensivo en
   computo, se debe considerar que sea escalable y soporte grandes
   volúmenes de ejecución.
   1. sistema de generación de programa de suministros
   2. sistema de ejecución
7. módulo de monitoreo y análisis

   recaba información de los sistemas de drones y estaciones
   meteorológicas, realiza un análisis de estos datos y calcula el
   estado de salud de los cultivos en las parcelas.

   1. sistema de obtención de imágenes
      1. sistema periódico de actualización de datos
         de acuerdo al plan del servicio del usuario (más
         configuraciones especiales por parcela) recopila
         periodicamente la información provista por el servicio de
         drones (la frecuencia depende tambien de estos parámetros).
      2. sistema de comunicacion con servicio de drones
      3. sistema de seleccion de servicios de drones
         este sistema determina, para cada combinación de
         {parcela, usuario, pedido especial} qué servicio de drones
         utilizar.
   2. sistema de monitoreo climatológico
      (se comunica con las microestaciones del INTA)
   3. sistema de análisis de imágenes
      procesa las imágenes gráficas y extrae de ellas los parámetros
      de temperatura, índice de biomasa, etc
   4. sistema de cálculo de salud
      en base a los parámetros actuales de una parcela y a los datos
      agronómicos de especie de la parcela, recalcula sus valores de
      salud.
8. módulo de actuación

   dado un pedido de actuación sobre una parcela (provisto por el
   modulo de ejecución de plan maestro), identifica a los actuadores
   (maquinaria) en su cercanía y les provee parámetros de acción para
   que se pongan en marcha y lleven a cabo las acciones. Permite
   manejar tanto maquinaria moderna automatizada como enviar
   información por email o SMS para el caso de maquinaria operada
   manualmente.
   1. sistema de comunicaciones
   2. sistema de gestión de tareas para maquinaria
      elige de acuerdo a los pedidos de actuación a realizar, escoge
      los dispositivos más cercanos al terreno objetivo y el scheduling de
      ejecución de las acciones.
   3. sistema de traduccion de mensajes para maquinaria
      en base a un formato estandar de pedido de actuación (con puntos
      GPS, valores en litros de sustancia a aplicar, etc), los
      traduce a un formato que puede entender cada modelo de
      maquinaria (por ejemplo secuencias de movimientos) o que pueda
      ser leido por un usuario (para el caso de actuaciones manuales).
9. módulo de gestión de planes maestros
   1. sistema de ABM de planes maestros
   2. sistema de gestión de licencias de planes
10. módulo de conocimiento de especies de cultivo

    contiene la información de las especies conocidas por el sistema
    (incluye información para empleo por parte del sistema de cálculo
    de salud)

* TODO WBS Proyecto (tentativo)
1. definición de arquitectura de componentes y conectores
2. relevamiento y definición de tecnologías
   1. lenguajes de programación
   2. sistemas de comunicaciones
   3. herramientas de versionado
   4. metodologías y herramientas de testing
3. relevamiento de tipos de maquinaria disponible

* todo
** DONE punto 8 : detallar el tema de comunicacion con actuadores
   por ejemplo es necesario para los actuadores en la region
   patagonica
** TODO ver bien la relación entre el ejecutor del PM y el actuador
** TODO detallar más subitems
